[package]
name = "swf_basic"
version = "0.1.0"
authors = ["Jon Hardie <jon@hardiesoft.com>"]
edition = "2018"

[dependencies]
gl = "0.6"
sdl2 = "0.32"
sdl2-sys = "0.32"

swf-parser = "0.7.0"
swf-tree = "0.7.0"

[dependencies.pathfinder_flash]
path = "../../flash"

[dependencies.pathfinder_geometry]
path = "../../geometry"

[dependencies.pathfinder_gl]
path = "../../gl"

[dependencies.pathfinder_gpu]
path = "../../gpu"

[dependencies.pathfinder_renderer]
path = "../../renderer"
