language: rust
addons:
  apt:
    packages:
    - libegl1-mesa-dev
    - libgtk-3-dev
    - libsdl2-dev
    - cmake
script:
  - cargo build
  - cargo test
  - rustup target add aarch64-unknown-linux-gnu
  - cargo build --target  aarch64-unknown-linux-gnu
env:
  global:
    - HARFBUZZ_SYS_NO_PKG_CONFIG=true
