[workspace]
members = [
    "font-renderer",
    "gfx-utils",
    "partitioner",
    "path-utils",
    "demo/server",
    "utils/area-lut",
    "utils/frontend",
    "utils/gamma-lut",
]

[patch.crates-io]
ring = { git = "https://github.com/SergioBenitez/ring", branch = "v0.12" }
