[workspace]
members = [
    "demo/common",
    "demo/native",
    "geometry",
    "gl",
    "gpu",
    "renderer",
    "simd",
    "svg",
    "ui",
    "utils/area-lut",
    "utils/gamma-lut",
    "utils/tile-svg",
    "utils/svg-to-skia"
]
