[package]
name = "tile-svg"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"

[features]
pf-no-simd = []

[dependencies]
arrayvec = "0.4"
byteorder = "1.2"
clap = "2.32"
euclid = "0.19"
fixedbitset = "0.1"
hashbrown = "0.1"
jemallocator = "0.1"
rayon = "1.0"
svgtypes = "0.3"
usvg = "0.4"

[dependencies.pathfinder_geometry]
path = "../../geometry"

[dependencies.pathfinder_renderer]
path = "../../renderer"

[dependencies.pathfinder_svg]
path = "../../svg"

[dev-dependencies]
quickcheck = "0.7"
rand = "0.5"
