[package]
name = "tile-svg"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
byteorder = "1.2"
clap = "2.32"
euclid = "0.19"
fixedbitset = "0.1"
hashbrown = "0.1"
jemallocator = "0.1"
lyon_geom = "0.12"
lyon_path = "0.12"
rayon = "1.0"
simdeez = "0.4"
svgtypes = "0.3"
usvg = "0.4"

[dependencies.pathfinder_geometry]
path = "../../geometry"

[dev-dependencies]
quickcheck = "0.7"
rand = "0.5"
