[package]
name = "pathfinder_server"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[dependencies]
app_units = "0.5"
base64 = "0.6"
bincode = "0.8"
euclid = "0.15"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.fontsan]
git = "https://github.com/servo/fontsan.git"

[dependencies.opentype-sanitizer-sys]
git = "https://github.com/pcwalton/opentype-sanitizer-sys.git"

[dependencies.pathfinder_font_renderer]
path = "../../font-renderer"

[dependencies.pathfinder_partitioner]
path = "../../partitioner"
