[package]
name = "pathfinder_geometry"
version = "0.3.0"
edition = "2018"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[dependencies]
arrayvec = "0.4"
bitflags = "1.0"
serde = "1.0"
serde_derive = "1.0"
smallvec = "0.6"

[dependencies.pathfinder_simd]
path = "../simd"
