[package]
name = "pathfinder_partitioner"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[lib]
name = "pathfinder_partitioner"

[dependencies]
bincode = "0.8"
bit-vec = "0.4"
byteorder = "1.2"
env_logger = "0.4"
euclid = "0.15"
half = "1.0"
log = "0.3"
serde = "1.0"
serde_derive = "1.0"

[dependencies.pathfinder_path_utils]
path = "../path-utils"
