[package]
name = "pathfinder_font_renderer"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[dependencies]
app_units = "0.5"
euclid = "0.15"
freetype-sys = "0.6"
log = "0.3"

[dependencies.pathfinder_path_utils]
path = "../path-utils"

[dev-dependencies]
env_logger = "0.4"
